jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id:          ${{ secrets.GCP_PROJECT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: infra
        run: terraform init \
               -backend-config="bucket=${{ secrets.GCP_PROJECT }}-raw" \
               -backend-config="prefix=tfstate"

      - name: Terraform Format Check
        working-directory: infra
        run: terraform fmt -check

      - name: Terraform Plan
        working-directory: infra
        run: terraform plan -out=tfplan
